name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
              echo ">>> Clonando Evolution API se necessÃ¡rio..."
              cd ~
              if [ ! -d "evolution-api" ]; then
                git clone https://github.com/EvolutionAPI/evolution-api.git
              fi

              echo ">>> Configurando arquivos da Evolution API..."
              cd evolution-api
              cp -n .env.example .env

              echo ">>> Subindo Evolution API (com redis e postgres) e criando a rede evolution-net..."
              docker compose up -d

              echo ">>> Esperando a rede evolution-net e serviÃ§os estarem prontos..."
              sleep 15

              echo ">>> Limpando cÃ³digo anterior do backend..."
              rm -rf ~/espaco-construir-backend
              git clone https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/Dev-Adrianoo/espaco-construir-backend.git ~/espaco-construir-backend

              echo ">>> Subindo backend conectado Ã  rede evolution-net..."
              cd ~/espaco-construir-backend
              docker compose up --build -d

              echo "ğŸ‰ Backend + Evolution API no ar com sucesso! ğŸ‰"